FROM python:3.11-slim
RUN pip3 install --quiet --no-cache-dir sherlock-project holehe
ADD https://raw.githubusercontent.com/mloaf201-josh/mloaf201-josh.github.io/main/osint_v7.py /app/server.py
EXPOSE 9193
CMD ["python3", "/app/server.py"]
